version: 0.0
os: linux
files:
  - source: /
    destination: /dz-bot
hooks:
  Install:
    - location: aws/scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: aws/scripts/application-stop.sh
      timeout: 300
      runas: root
