version: '3.8'
name: dz-bot


x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  app:
    build: .
    depends_on:
     db:
       condition: service_healthy
    volumes:
      - ./:/app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - sst-gpt-network

  db:
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    logging: *default-logging
    networks:
      - sst-gpt-network

volumes:
  mysql-data:

networks:
  sst-gpt-network:
    external: true
