name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  APP_NAME: bot-app
  DEPLOY_GROUP: bot-deploy-group

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          commit_hash=`git rev-parse HEAD`
          aws deploy create-deployment --application-name ${{ env.APP_NAME }} --deployment-group-name ${{ env.DEPLOY_GROUP }} --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
